---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

#   - distro: debian9
 - distro: debian8
#   - distro: ubuntu1804
#   - distro: ubuntu1604

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/buluma/222d4b8a425069e77287aecb12b56506/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Simulate mail program exists
  - ${DOCKER} touch /usr/local/bin/mail

  # Make sure automysqlbackup is installed.
  - ${DOCKER} test -e /usr/local/bin/automysqlbackup

  # Check if automysqlbackup cronjob exists
  - ${DOCKER} test -e /etc/cron.d/automysqlbackup

  # Simulate automysqlbackup cron
  - ${DOCKER} /usr/local/bin/automysqlbackup-wrapper.sh

  # Check if automysqlbackup cronjob worked
  - ${DOCKER} test -e /var/backup/db/latest/daily_travis_testdb.sql.gz

  # Check if privileges cronjob exists
  - ${DOCKER} test -e /etc/cron.d/mysql_priviledges

  # Simulate privileges cron
  - ${DOCKER} /usr/local/bin/privileges-wrapper.sh

  # Check if privileges cronjob worked
  - ${DOCKER} test -e /var/backup/db/privileges.sql.gz


after_failure:
  - ${DOCKER} ls -la /var/backup/db/latest
  - ${DOCKER} tail -n 150 /var/log/syslog
  - ${DOCKER} ls -la /var/log/automysqlbackup/
  - ${DOCKER} cat /var/log/automysqlbackup/*.log
  - ${DOCKER} /usr/local/bin/automysqlbackup
